target-version = "py312"
line-length = 100

[lint]
select = ["E", "F", "W", "I", "UP", "B", "SIM", "RUF"]
ignore = ["E501"]

[lint.isort]
known-first-party = ["collage_backend"]

[format]
quote-style = "double"
indent-style = "space"
